=== wackadoo/battle-calc-prototyping/backend/BattleCalcDemo/rules.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Rules (General, Languages?, ResourceTypes?, BuildingTypes?, ScienceTypes?, UnitCategories?, UnitTypes?)>
<!ELEMENT General (Game, Version, Languages)>
<!ELEMENT Game (#PCDATA)>
<!ATTLIST Game 
  branch CDATA #REQUIRED
  tag CDATA #IMPLIED
>
<!ELEMENT Version EMPTY>
<!ATTLIST Version 
  major CDATA #REQUIRED
  minor CDATA #REQUIRED
  build CDATA #REQUIRED
>

<!--Languages-->
<!ELEMENT Languages (Language*)>
<!ELEMENT Language (#PCDATA)>
<!ATTLIST Language locale ID #REQUIRED>

<!--Types-->
<!ELEMENT ResourceTypes (Resource*)>
<!ELEMENT BuildingTypes (Building*)>
<!ELEMENT ScienceTypes (Science*)>
<!ELEMENT UnitTypes (Unit*)>
<!ELEMENT UnitCategories (UnitCategory*)>

<!--Resource-->
<!ELEMENT Resource (Name+, RatingValue, TakeoverValue, StealRatio, DestroyRatio, SafeStorage, MaxStorage, Production)>
<!ATTLIST Resource id ID #REQUIRED hidden (0 | 1) "0">

<!--Building-->
<!ELEMENT Building (Name+, Description+, Position?, RatingValue, Cost*, ProductionTime, MaxDevelopmentLevel, (Requirement | EffectReq)*)>
<!ATTLIST Building id ID #REQUIRED hidden (0 | 1) "0">

<!--Science-->
<!ELEMENT Science (Name+, Description+, Position?, Cost*, ProductionTime, MaxDevelopmentLevel, (Requirement | EffectReq)*)>
<!ATTLIST Science id ID #REQUIRED hidden (0 | 1) "0">

<!--Unit-->
<!ELEMENT UnitCategory (Name+, Description+, Position?, Ability*, TargetPriorities?)>
<!ATTLIST UnitCategory 
  id ID #REQUIRED 
>
<!ELEMENT Unit (Name+, Description+, Position?, Velocity, ActionPoints, Initiative, Attack, CriticalDamage, Armor, Overrunnable, Hitpoints, Effectiveness*, Encumbrance*)>
<!ATTLIST Unit 
  id ID #REQUIRED 
  category IDREF #REQUIRED
>

<!ELEMENT TargetPriorities (TargetList, TargetList)>
<!ATTLIST TargetPriorities
	testType CDATA #REQUIRED
	testCategory IDREF #IMPLIED
>

<!ELEMENT TargetList (Target)>
<!ELEMENT Target EMPTY>
<!ATTLIST Target
 id IDREF #REQUIRED
>


<!--Webinterface: Production-->
<!ELEMENT Cost (#PCDATA | object)*>
<!ATTLIST Cost id IDREF #REQUIRED>
<!ELEMENT object EMPTY>
<!ATTLIST object id IDREF #REQUIRED>

<!--Ability-->
<!ELEMENT Ability EMPTY>
<!ATTLIST Ability
 id CDATA #REQUIRED
>

<!--Requirement-->
<!ELEMENT Requirement EMPTY>
<!ATTLIST Requirement id IDREF #REQUIRED min CDATA "0" max CDATA #IMPLIED>
<!ELEMENT EffectReq EMPTY>
<!ATTLIST EffectReq id IDREF #REQUIRED min CDATA #IMPLIED max CDATA #IMPLIED>

<!--Encumbrance-->
<!ELEMENT Encumbrance EMPTY>
<!ATTLIST Encumbrance id IDREF #REQUIRED value CDATA #REQUIRED>

<!--Combat-->
<!ELEMENT Initiative (#PCDATA)>
<!ELEMENT Attack (#PCDATA)>
<!ELEMENT CriticalDamage (#PCDATA)>
<!ATTLIST CriticalDamage 
  chance CDATA #REQUIRED
>
<!ELEMENT Armor (#PCDATA)>
<!ELEMENT Hitpoints (#PCDATA)>
<!ELEMENT Overrunnable (#PCDATA)>
<!ELEMENT Effectiveness (#PCDATA)>
<!ATTLIST Effectiveness 
  category IDREF #REQUIRED
>

<!--Common Leafs-->
<!ELEMENT Description (p*)>
<!ATTLIST Description lang IDREF "en_US">
<!ELEMENT Name (#PCDATA)>
<!ATTLIST Name lang IDREF "en_US">
<!ELEMENT p (#PCDATA)>
<!ELEMENT Position (#PCDATA)>
<!ELEMENT Velocity (#PCDATA)>
<!ELEMENT ActionPoints (#PCDATA)>

<!--entities-->
<!ENTITY apst "&amp;#39;">
<!ENTITY auml "&amp;auml;">
<!ENTITY ouml "&amp;ouml;">
<!ENTITY uuml "&amp;uuml;">
<!ENTITY Auml "&amp;Auml;">
<!ENTITY Ouml "&amp;Ouml;">
<!ENTITY Uuml "&amp;Uuml;">
<!ENTITY szlig "&amp;szlig;">

=== wackadoo/battle-calc-prototyping/backend/BattleCalcDemo/units/rules_units_sabre_riders.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

<Unit id="sabre_riders" category="unitcategory_cavalry">
      <Name>Sabretooth-Riders</Name>
      <Name lang="de_DE">Säbelzahnreiter</Name>
      <Description lang="de_DE">
        <p>Viele fürchten die Reittiere mehr als die eigentlichen Reiter...</p> 
      </Description>
      <Description lang="en_US">
        <p>It's not so much the riders themselves that are feared...</p>
      </Description>
      <Cost id="resource_stone" round="true">2</Cost>  
      <Cost id="resource_wood" round="true">10</Cost>    
      <Cost id="resource_fur" round="true">4</Cost>    
      <ProductionTime shortenable="true">300</ProductionTime>  
	  <Requirement id="building_stud" min_level="11" />
      <Velocity>1.4</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>28</Initiative>
      <Attack>21</Attack>
      <CriticalDamage chance="0.02">14</CriticalDamage>
      <Armor>15</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>140</Hitpoints>
      <Effectiveness category="unitcategory_infantry">0.4</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">0.6</Effectiveness>
      <Effectiveness category="unitcategory_artillery">1</Effectiveness>
      <Effectiveness category="unitcategory_siege">0.4</Effectiveness>     
    </Unit>

=== wackadoo/battle-calc-prototyping/backend/BattleCalcDemo/rules_unitcategories.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "rules.dtd">

  <UnitCategories>
    <UnitCategory id="unitcategory_infantry">
      <Name>Infantry</Name>
      <Name lang="de_DE">Fußtruppen</Name>
      <Description>
        <p>English description here.</p>
      </Description>
      <Description lang="de_DE">
        <p>Infanterie ist die Basiseinheit in jeder Truppe. Sie schützt Fernkämpfer vor direkt Angriffen und kann, wenn in ausreichender Zahl vorhanden, auch Flankenangriffe abwehren.</p>
      </Description>
      <Ability id="prevent-flanking" />
			<TargetPriorities testType="no_test">
				<TargetList>
					<Target id="unitcategory_infantry" />
					<Target id="unitcategory_cavalry" />
					<Target id="unitcategory_artillery" />
					<Target id="unitcategory_siege" />
				</TargetList>
			</TargetPriorities>
    </UnitCategory>
    <UnitCategory id="unitcategory_cavalry">
      <Name>cavalry</Name>
      <Name lang="de_DE">Reiter</Name>
      <Description>
        <p>English description here.</p>
      </Description>
      <Description lang="de_DE">
        <p>Berittene Einheiten bewegen sich schnell auf dem Schlachtfeld, und sind als einzige in der Lage, die gegnerischen Fußtruppen zu umgehen und feindliche Fernkämpfer direkt anzugreifen (Flankenangriff).</p>
      </Description>
      <Ability id="flanking" />
			<TargetPriorities testType="line_size_test" testCategory="infantry">
				<TargetList>
					<Target id="unitcategory_cavalry" />
					<Target id="unitcategory_artillery" />
					<Target id="unitcategory_infantry" />
					<Target id="unitcategory_siege" />
				</TargetList>
				<TargetList>
					<Target id="unitcategory_cavalry" />
					<Target id="unitcategory_infantry" />
					<Target id="unitcategory_artillery" />
					<Target id="unitcategory_siege" />
				</TargetList>
			</TargetPriorities>
    </UnitCategory>
    <UnitCategory id="unitcategory_artillery">
      <Name>Ranged Troops</Name>
      <Name lang="de_DE">Fernkämpfer</Name>
      <Description>
        <p>English description here.</p>
      </Description>
      <Description lang="de_DE">
        <p>Die Fernkämpfer schießen aus sicherer Distanz auf den Gegner, vorzugsweise auf Fußsoldaten. Im Nahkampf sind sie extrem anfällig.</p>
      </Description>
			<TargetPriorities testType="no_test">
				<TargetList>
					<Target id="unitcategory_infantry" />
					<Target id="unitcategory_artillery" />
					<Target id="unitcategory_cavalry" />
					<Target id="unitcategory_siege" />
				</TargetList>
			</TargetPriorities>
    </UnitCategory>
    <UnitCategory id="unitcategory_siege">
      <Name>Siege Weapons</Name>
      <Name lang="de_DE">Belagerungsgeräte</Name>
      <Description>
        <p>Siege Weapons support armies in battle against settlements.</p>
      </Description>
      <Description lang="de_DE">
        <p>Belagerungsgerät dient der Unterstützung im Kampf gegen Siedlungen.</p>
      </Description>
      <!--here we need a test: are there legal target buildings in the enemy faction? special abilities are on a per unit basis -->
			<TargetPriorities testType="no_test">
				<TargetList>
					<Target id="unitcategory_siege" />
					<Target id="unitcategory_artillery" />
					<Target id="unitcategory_infantry" />
					<Target id="unitcategory_cavalry" />
				</TargetList>
			</TargetPriorities>
    </UnitCategory>
  </UnitCategories>

=== wackadoo/battle-calc-prototyping/backend/BattleCalcDemo/units/rules_units_thrower.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

    <Unit id="thrower" category="unitcategory_artillery">
      <Name>Pebble Thrower</Name>
      <Name lang="de_DE">Kieselsteinwerfer</Name>
  <Flavour lang="en_US">
    <p>Kills opposing units.</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Kämpft gegen andere Einheiten.</p>
  </Flavour>
      <Description lang="de_DE">
        <p>Große Steine, kleine Steine, ein Kieselsteinwerfer mag sie alle, solange er sie jemandem an den Kopf werfen kann. Ok, zugegeben, die kleinen mag er ein bisschen lieber. Nichtsdestotrotz kann er moderaten kritischen Schaden zufügen - denn, wie jeder weiß, das kann auch ins Auge gehen.</p> 
      </Description>
      <Description lang="en_US">
        <p>Small Stones, big Stones, a Peeble Thrower likes them all, as long as he can throw them at people. Ok, granted, the small ones are slightly prefered... Nevertheless, he may inflict moderate critical damage by sometimes hitting an opponent's eye.'</p>
      </Description>
      <Cost id="resource_stone" round="true">12</Cost>  
      <Cost id="resource_fur" round="true">2</Cost>    
      <ProductionTime shortenable="true">500</ProductionTime>  
      <Velocity>1</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>8</Initiative>
      <Attack>18</Attack>
      <CriticalDamage chance="0.01">10</CriticalDamage>
      <Armor>2</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>90</Hitpoints>
      <Effectiveness category="unitcategory_infantry">1</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">0.3</Effectiveness>
      <Effectiveness category="unitcategory_artillery">0.75</Effectiveness>
      <Effectiveness category="unitcategory_siege">0.75</Effectiveness>   
	  
    </Unit>

=== wackadoo/battle-calc-prototyping/backend/BattleCalcDemo/units/rules_units_neandertaler.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

<Unit id="neanderthal" category="unitcategory_infantry">
  <Name>Neanderthal</Name>
  <Name lang="de_DE">Neandertaler</Name>
  <Description lang="de_DE">
    <p>Wilder Vormenschenstamm.</p>		
  </Description>
  <Description lang="en_US">
    <p>Fierce Fighters.</p>
  </Description>
  <Flavour lang="en_US">
    <p>Don't talk, fight.</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Reden nicht, handeln. Ã„h, schlagen.</p>
  </Flavour>
	<Requirement id="building_stud" min_level="100" />
  <Cost id="resource_stone" round="true">40</Cost>  
  <Cost id="resource_wood" round="true">20</Cost>    
  <Cost id="resource_fur" round="true">12</Cost>    
  <ProductionTime shortenable="true">1200</ProductionTime>  
  <Velocity>1</Velocity>
  <ActionPoints>4</ActionPoints>
  <Initiative>16</Initiative>
  <Attack>15</Attack>
  <CriticalDamage chance="0.01">2</CriticalDamage>
  <Armor>0</Armor>
  <Overrunnable>false</Overrunnable>
  <Hitpoints>90</Hitpoints>
  <Effectiveness category="unitcategory_infantry">1.0</Effectiveness>
  <Effectiveness category="unitcategory_cavalry">0.8</Effectiveness>
  <Effectiveness category="unitcategory_artillery">1.0</Effectiveness>
  <Effectiveness category="unitcategory_siege">1.0</Effectiveness>    
</Unit>

=== wackadoo/battle-calc-prototyping/backend/BattleCalcDemo/units/rules_units_skewer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

    <Unit id="skewer" category="unitcategory_infantry">
      <Name>Spit Bearer</Name>
      <Name lang="de_DE">Bratspießträger</Name>
      <Description lang="de_DE">
        <p>Der Umgang mit der Waffe ist schnell gelernt: Das spitze Ende muss nach vorn!</p> 
		<p>Richtig angewendet tropfen fettige Flüssigkeiten vom Spieß, genau genommen das Blut seiner Feinde</p>
      </Description>
      <Description lang="en_US">
        <p>Skewer Crew training 101: stick'em with the pointy end!</p> 
		<p>Greasy liquids are dripping from the spits, correctly used it is the enemies‘ blood.</p>
      </Description>
      <Cost id="resource_stone" round="true">2</Cost>  
      <Cost id="resource_wood" round="true">10</Cost>    
      <Cost id="resource_fur" round="true">4</Cost>    
      <ProductionTime shortenable="true">300</ProductionTime>   
	  <Requirement id="building_firing_range" min_level="21" />	  
      <Velocity>1</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>15</Initiative>
      <Attack>16</Attack>
      <CriticalDamage chance="0.01" >11</CriticalDamage>
      <Armor>3</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>90</Hitpoints>
      <Effectiveness category="unitcategory_infantry">0.9</Effectiveness><!-- due to the long weapon reduced effectivity against infantry but full effectivity against cavalry. a standard infantry (short weapon) would have effectivity 1 against infantry and reduced effictivity against cavalry, right?! -->
      <Effectiveness category="unitcategory_cavalry">1.2</Effectiveness>
      <Effectiveness category="unitcategory_artillery">0.6</Effectiveness>
      <Effectiveness category="unitcategory_siege">0.6</Effectiveness>     
    </Unit>

=== wackadoo/battle-calc-prototyping/backend/BattleCalcDemo/units/rules_units_tree_huggers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

 <Unit id="tree_huggers" category="unitcategory_infantry">
      <Name>Tree Huggers</Name>
      <Name lang="de_DE">Baum-Brutalo</Name>
  <Flavour lang="en_US">
    <p>Kills opposing units.</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Kämpft gegen andere Einheiten.</p>
  </Flavour>
      <Description lang="de_DE">
        <p>Groß, stark, sauber rasierter Bart. Ein Baum-Brutalo legt sehr großen Wert auf sein Äußeres.</p> 
		<p>In der Schlacht bietet der Baum-Brutalo ein seltsames Schauspiel. Umhüllt von den rauschen Blättern seines Kampfbaumes wirbelt der Baum-Brutalo durch die gegnerischen Reihen wie ein Säberlzahntiger, der sich den Schwanz geklammt hat. Nicht den flauschigen, den anderen...</p>
      </Description>
      <Description lang="en_US">
        <p>What Tree-Huggers lack in brains, they make up for with sheer strength.</p>
		<p>Telling by an unverified legend, those guys are brought up in a tree-nursery.</p>
      </Description>
      <Cost id="resource_stone" round="true">2</Cost>  
      <Cost id="resource_wood" round="true">10</Cost>    
      <Cost id="resource_fur" round="true">4</Cost>    
      <ProductionTime shortenable="true">300</ProductionTime>  
	  <Requirement id="building_barracks" min_level="11" /> 
      <Velocity>0.95</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>14</Initiative>
      <Attack>20</Attack>
      <CriticalDamage chance="0.02">9</CriticalDamage>
      <Armor>4</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>140</Hitpoints>
      <Effectiveness category="unitcategory_infantry">0.8</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">1</Effectiveness>
      <Effectiveness category="unitcategory_artillery">0.8</Effectiveness>
      <Effectiveness category="unitcategory_siege">1</Effectiveness> 
    </Unit>

=== wackadoo/battle-calc-prototyping/backend/BattleCalcDemo/units/rules_units_ram.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

	  <Unit id="ram" category="unitcategory_siege">
      <Name>Battering Ram</Name>
      <Name lang="de_DE">Rammbock</Name>
      <Description lang="de_DE">
        <p>Nur wenige wissen, dass der Name Rammbock von einem pr√§historischen Tier aus der Unterfamilie der ziegenartigen (caprinae) abstammt.</p> 
      </Description>
      <Description lang="en_US">
        <p>The battering ram is the lockpick of choice to open doors, gates and cracking down fortifications.</p>
      </Description>
      <Cost id="resource_stone" round="true">2</Cost>  
      <Cost id="resource_wood" round="true">10</Cost>    
      <Cost id="resource_fur" round="true">4</Cost>    
      <ProductionTime shortenable="true">300</ProductionTime>  
      <Velocity>0.9</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>16</Initiative>
      <Attack>15</Attack>
      <CriticalDamage chance="0.01">2</CriticalDamage>
      <Armor>0</Armor>
      <!--needs special ability: destroy wall level -->
      <Overrunnable>true</Overrunnable>
      <Hitpoints>90</Hitpoints>
      <Effectiveness category="unitcategory_infantry">0.2</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">0.1</Effectiveness>
      <Effectiveness category="unitcategory_artillery">0.2</Effectiveness>
      <Effectiveness category="unitcategory_siege">1</Effectiveness>     
    </Unit>

=== wackadoo/battle-calc-prototyping/backend/BattleCalcDemo/units/rules_units_clubbers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

<Unit id="clubbers" category="unitcategory_infantry">
  <Name>Club Warrior</Name>
  <Name lang="de_DE">Keulenkrieger</Name>
  
  <Description lang="de_DE">
    <p>Eine Keule in der Hand und immer an vorderster Front. Keulenkrieger brauchen nicht viel für ein glücklcihes Leben.</p>
    <p>Zudem ist dieses meist sehr kurz.</p>		
  </Description>
  <Description lang="en_US">
    <p>Actually armed with a club, the mace-men are in the front rank of all armies.</p>
  </Description>
  <Flavour lang="en_US">
    <p>Kills opposing units.</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Kämpft gegen andere Einheiten.</p>
  </Flavour>
  <Cost id="resource_stone" round="true">40</Cost>  
  <Cost id="resource_wood" round="true">20</Cost>    
  <Cost id="resource_fur" round="true">12</Cost>    
  <ProductionTime shortenable="true">1200</ProductionTime>  
  <Velocity>1</Velocity>
  <ActionPoints>4</ActionPoints>
  <Initiative>16</Initiative>
  <Attack>15</Attack>
  <CriticalDamage chance="0.01">2</CriticalDamage>
  <Armor>0</Armor>
  <Overrunnable>true</Overrunnable>
  <Hitpoints>90</Hitpoints>
  <Effectiveness category="unitcategory_infantry">0.9</Effectiveness>
  <Effectiveness category="unitcategory_cavalry">0.9</Effectiveness>
  <Effectiveness category="unitcategory_artillery">0.7</Effectiveness>
  <Effectiveness category="unitcategory_siege">0.8</Effectiveness>    
</Unit>
