=== wackadoo/battle-calc-prototyping/backend/BattleCalcDemo/rules.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Rules (General, Languages?, ResourceTypes?, BuildingTypes?, ScienceTypes?, UnitCategories?, UnitTypes?)>
<!ELEMENT General (Game, Version, Languages)>
<!ELEMENT Game (#PCDATA)>
<!ATTLIST Game 
  branch CDATA #REQUIRED
  tag CDATA #IMPLIED
>
<!ELEMENT Version EMPTY>
<!ATTLIST Version 
  major CDATA #REQUIRED
  minor CDATA #REQUIRED
  build CDATA #REQUIRED
>

<!--Languages-->
<!ELEMENT Languages (Language*)>
<!ELEMENT Language (#PCDATA)>
<!ATTLIST Language locale ID #REQUIRED>

<!--Types-->
<!ELEMENT ResourceTypes (Resource*)>
<!ELEMENT BuildingTypes (Building*)>
<!ELEMENT ScienceTypes (Science*)>
<!ELEMENT UnitTypes (Unit*)>
<!ELEMENT UnitCategories (UnitCategory*)>

<!--Resource-->
<!ELEMENT Resource (Name+, RatingValue, TakeoverValue, StealRatio, DestroyRatio, SafeStorage, MaxStorage, Production)>
<!ATTLIST Resource id ID #REQUIRED hidden (0 | 1) "0">

<!--Building-->
<!ELEMENT Building (Name+, Description+, Position?, RatingValue, Cost*, ProductionTime, MaxDevelopmentLevel, (Requirement | EffectReq)*)>
<!ATTLIST Building id ID #REQUIRED hidden (0 | 1) "0">

<!--Science-->
<!ELEMENT Science (Name+, Description+, Position?, Cost*, ProductionTime, MaxDevelopmentLevel, (Requirement | EffectReq)*)>
<!ATTLIST Science id ID #REQUIRED hidden (0 | 1) "0">

<!--Unit-->
<!ELEMENT UnitCategory (Name+, Description+, Position?, Ability*, TargetPriorities?)>
<!ATTLIST UnitCategory 
  id ID #REQUIRED 
>
<!ELEMENT Unit (Name+, Description+, Position?, Velocity, ActionPoints, Initiative, Attack, CriticalDamage, Armor, Overrunnable, Hitpoints, Effectiveness*, Encumbrance*)>
<!ATTLIST Unit 
  id ID #REQUIRED 
  category IDREF #REQUIRED
>

<!ELEMENT TargetPriorities (TargetList, TargetList)>
<!ATTLIST TargetPriorities
	testType CDATA #REQUIRED
	testCategory IDREF #IMPLIED
>

<!ELEMENT TargetList (Target)>
<!ELEMENT Target EMPTY>
<!ATTLIST Target
 id IDREF #REQUIRED
>


<!--Webinterface: Production-->
<!ELEMENT Cost (#PCDATA | object)*>
<!ATTLIST Cost id IDREF #REQUIRED>
<!ELEMENT object EMPTY>
<!ATTLIST object id IDREF #REQUIRED>

<!--Ability-->
<!ELEMENT Ability EMPTY>
<!ATTLIST Ability
 id CDATA #REQUIRED
>

<!--Requirement-->
<!ELEMENT Requirement EMPTY>
<!ATTLIST Requirement id IDREF #REQUIRED min CDATA "0" max CDATA #IMPLIED>
<!ELEMENT EffectReq EMPTY>
<!ATTLIST EffectReq id IDREF #REQUIRED min CDATA #IMPLIED max CDATA #IMPLIED>

<!--Encumbrance-->
<!ELEMENT Encumbrance EMPTY>
<!ATTLIST Encumbrance id IDREF #REQUIRED value CDATA #REQUIRED>

<!--Combat-->
<!ELEMENT Initiative (#PCDATA)>
<!ELEMENT Attack (#PCDATA)>
<!ELEMENT CriticalDamage (#PCDATA)>
<!ATTLIST CriticalDamage 
  chance CDATA #REQUIRED
>
<!ELEMENT Armor (#PCDATA)>
<!ELEMENT Hitpoints (#PCDATA)>
<!ELEMENT Overrunnable (#PCDATA)>
<!ELEMENT Effectiveness (#PCDATA)>
<!ATTLIST Effectiveness 
  category IDREF #REQUIRED
>

<!--Common Leafs-->
<!ELEMENT Description (p*)>
<!ATTLIST Description lang IDREF "en_US">
<!ELEMENT Name (#PCDATA)>
<!ATTLIST Name lang IDREF "en_US">
<!ELEMENT p (#PCDATA)>
<!ELEMENT Position (#PCDATA)>
<!ELEMENT Velocity (#PCDATA)>
<!ELEMENT ActionPoints (#PCDATA)>

<!--entities-->
<!ENTITY apst "&amp;#39;">
<!ENTITY auml "&amp;auml;">
<!ENTITY ouml "&amp;ouml;">
<!ENTITY uuml "&amp;uuml;">
<!ENTITY Auml "&amp;Auml;">
<!ENTITY Ouml "&amp;Ouml;">
<!ENTITY Uuml "&amp;Uuml;">
<!ENTITY szlig "&amp;szlig;">

=== wackadoo/battle-calc-prototyping/backend/BattleCalcDemo/units/rules_units_slingshot_warrior.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

    <Unit id="slingshot_warrior" category="unitcategory_artillery">
      <Name>Slingshot Warrior</Name>
      <Name lang="de_DE">Steinschleuderer</Name>
  <Flavour lang="en_US">
    <p>Kills opposing units.</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Je hübscher die Schleuder, desto tödlicher auch der Steinschleuderer. Ursache hierfür ist weniger die Schleuder als die natürliche Selektion unter den Steinschleuderern. Wer hat die schönste Schleuder? Die Überlebenden!</p>
	</Flavour>
      <Description lang="de_DE">
    <p>Der Steinschleuderer trägt eine große Lederschleuder. Mit Hilfe dieser Schleuder schleudert der Steinschleuderer dem Gegner Steine entgegen.</p>
    <p>Ausschlaggebend für die Zielsicherheit ist dabei zum einen die Technik. Zwei bis drei Schwünge und dann am Scheitelpunkt mit einem Ruck den Stein schleudern. Zum anderen - und dies behaupten vor allem die Anfänger- ist die Art der Schleuder wichtig. Hochwertigere Ledersorten mit einer einwandfreien Verarbeitung und schönen Verzierungen treffen besser.</p>
	<p>Viele Tests konnten dies nicht belegen, dennoch sind die hochwertig verzierten Schleudern eine begehrte Beute. Sowohl beim Gegner als auch bei den eigenen Steinschleuderern.</p>
	  </Description>
      <Description lang="en_US">
        <p>Small Stones, big Stones, a Peeble Thrower likes them all, as long as he can throw them at people. Ok, granted, the small ones are slightly prefered... Nevertheless, he may inflict moderate critical damage by sometimes hitting an opponent's eye.'</p>
      </Description>
      <Cost id="resource_stone" round="true">16</Cost>  
	  <Cost id="resource_wood" round="true">4</Cost> 
      <Cost id="resource_fur" round="true">12</Cost>    
      <ProductionTime shortenable="true">500</ProductionTime>
	  <Requirement id="building_firing_range" min_level="11" />	  
      <Velocity>1</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>8</Initiative>
      <Attack>18</Attack>
      <CriticalDamage chance="0.01">10</CriticalDamage>
      <Armor>2</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>50</Hitpoints>
      <Effectiveness category="unitcategory_infantry">1</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">1.1</Effectiveness>
      <Effectiveness category="unitcategory_artillery">0.75</Effectiveness>
      <Effectiveness category="unitcategory_siege">0.5</Effectiveness>   
	  
    </Unit>

=== wackadoo/battle-calc-prototyping/backend/BattleCalcDemo/units/rules_units_catapult.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">
    <Unit id="catapult" category="unitcategory_siege">
      <Name>Catapult</Name>
      <Name lang="de_DE">Katapult</Name>
      <Description lang="de_DE">
        <p>Das Basismodell 'Catabilly' zum selber zusammenbauen, unschlagbar gÃ¼nstig.</p> 
      </Description>
      <Description lang="en_US">
        <p>The catapults take the cake in every intense battle because of their devastating damage.</p>
      </Description>
      <Cost id="resource_stone" round="true">2</Cost>  
      <Cost id="resource_wood" round="true">10</Cost>    
      <Cost id="resource_fur" round="true">4</Cost>    
      <ProductionTime shortenable="true">300</ProductionTime> 
	 <Requirement id="building_workshop" min_level="11" />	  
      <Velocity>0.7</Velocity>
      <ActionPoints>4</ActionPoints>
      <Initiative>16</Initiative>
      <Attack>15</Attack>
      <CriticalDamage chance="0.01">2</CriticalDamage>
      <Armor>0</Armor>
      <!--needs special ability: destroy semi-random building level-->
      <Overrunnable>true</Overrunnable>
      <Hitpoints>90</Hitpoints>
      <Effectiveness category="unitcategory_infantry">0.2</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">0.1</Effectiveness>
      <Effectiveness category="unitcategory_artillery">0.2</Effectiveness>
      <Effectiveness category="unitcategory_siege">1</Effectiveness>     
    </Unit>

=== wackadoo/battle-calc-prototyping/backend/BattleCalcDemo/units/rules_units_light_cavalry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rules SYSTEM "../rules.dtd">

    <Unit id="light_cavalry" category="unitcategory_cavalry">
      <Name>Ostrich Riders</Name>
      <Name lang="de_DE">Straußenreiter</Name>
  <Flavour lang="en_US">
    <p>Kills opposing units.</p>
  </Flavour>
  <Flavour lang="de_DE">
    <p>Kämpft gegen andere Einheiten.</p>
  </Flavour>
      <Description lang="de_DE">
        <p>Strauße sind nicht nur lecker sondern auch gute und schnelle Kämpfer. Die Straußenreiter sind äußerst schnell, dafür aber nur schwach gepanzert.</p> 
      </Description>
      <Description lang="en_US">
        <p>Ostrichs are not only delicious but also excellent and fast animals to be used in combats. Ostrich riders are very quick, but only lightly armored.</p>
      </Description>
      <Cost id="resource_stone" round="true">2</Cost>  
      <Cost id="resource_wood" round="true">10</Cost>    
      <Cost id="resource_fur" round="true">4</Cost>    
      <ProductionTime shortenable="true">300</ProductionTime>  
  	  <Velocity>1.5</Velocity>
      <ActionPoints>5</ActionPoints>
      <Initiative>26</Initiative>
      <Attack>16</Attack>
      <CriticalDamage chance="0.01">10</CriticalDamage>
      <Armor>3</Armor>
      <Overrunnable>true</Overrunnable>
      <Hitpoints>95</Hitpoints>
      <Effectiveness category="unitcategory_infantry">0.3</Effectiveness>
      <Effectiveness category="unitcategory_cavalry">0.75</Effectiveness>
      <Effectiveness category="unitcategory_artillery">1</Effectiveness>
      <Effectiveness category="unitcategory_siege">0.4</Effectiveness>   
    </Unit>
